spring.application.name=demo
spring.datasource.url=jdbc:h2:file:./data/h2
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#jwt
segredo.jwt=${JWT_SECRET:12345678}
jwt.issuer=${JWT_ISSUER:CONSERTOS JOELMA}